name: Publish Play Version to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker login -u jayfong -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build -t jayfong/yapi:latest .
          docker build -t jayfong/yapi:play -f ./Dockerfile.web .
          docker push jayfong/yapi:play
